# Generated by Django 6.0.3 on 2026-04-11 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Movie',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Nota precisa ser maior que 0 estrelas'), django.core.validators.MaxValueValidator(5, 'Nota precisa ser menor que 5 estrelas')]),
        ),
    ]
